version: "3.8"

services:
  generator:
    image: golang:latest
    working_dir: /app
    command: ["go", "run", "internal/cmd/generator/main.go"]
    volumes:
      - ".:/app"
    profiles:
      - manual

  database:
    image: postgres:14-alpine
    environment:
      - POSTGRES_USER=casino
      - POSTGRES_PASSWORD=casino
    ports:
      - "5432:5432"
    volumes:
      - "./db:/db"
